#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        	       6
bspc config window_gap          	       16 
bspc config -m eDP1 bottom_padding    	 34


# bspc config active_border_color \#FFFFFF
# bspc config normal_border_color '#000000'
bspc config focused_border_color \#b9d7ea;

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config focus_follows_pointer true

# General
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# KDE
bspc rule -a plasmashell state=floating border=off layer=normal focus=off
bspc rule -a Plasma state=floating focus=off
bspc rule -a plasma-desktop state=floating focus=off
bspc rule -a krunner state=floating border=off
bspc rule -a Kmix state=floating focus=off
bspc rule -a Klipper state=floating focus=off
bspc rule -a Plasmoidviewer state=floating
